init:
  - git config --global core.autocrlf true

branches:
  except:
    - /travis-.*/

build_script: 
  - ps: .\build.ps1 -Target "Appveyor" -Configuration "Debug"
  
# disable built-in tests.
test: off

artifacts:
- path: package\*.zip
- path: package\*.nupkg
