image: Previous Visual Studio 2022

build_script: 
  - ps: .\build.ps1 --target=AppVeyor --Configuration=Release
  
# disable built-in tests.
test: false

artifacts:
- path: package\*.zip
- path: package\*.nupkg

environment:
  MYGET_API_KEY:
    secure: wtAvJDVl2tfwiVcyLExFHLvZVfUWiQRHsfdHBFCNEATeCHo1Nd8JP642PfY8xhji
  NUGET_API_KEY:
    secure: 6lmjTFOrs5IZbOR70rmQNSOuFMPKGxA88/TuGAm1X3mspgj5bn1rnbN/iqTIC2Le
  CHOCO_API_KEY:
    secure: aDsu1U+umVYFVybjkBVtVQsatSj3QKbD7VkGQci9mNF3493g9Giao/GABISIaHjT
  GITHUB_PASSWORD:
    secure: 2eNz23Eb1L40g2LPmlPqog==
  GITHUB_ACCESS_TOKEN:
    secure: RJ6sKRBZzwXz8JQvj8zcp45mkHNDad1UlvmfCsiVx63V9/pXHcm2Y2Lg/G/Vyhlz
