//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCentric.Gui.Model.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class ErrorDisplaySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ErrorDisplaySettings defaultInstance = ((ErrorDisplaySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ErrorDisplaySettings())));
        
        public static ErrorDisplaySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SplitterPosition {
            get {
                return ((int)(this["SplitterPosition"]));
            }
            set {
                this["SplitterPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordWrapEnabled {
            get {
                return ((bool)(this["WordWrapEnabled"]));
            }
            set {
                this["WordWrapEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ToolTipsEnabled {
            get {
                return ((bool)(this["ToolTipsEnabled"]));
            }
            set {
                this["ToolTipsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SourceCodeDisplay {
            get {
                return ((bool)(this["SourceCodeDisplay"]));
            }
            set {
                this["SourceCodeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical")]
        public global::System.Windows.Forms.Orientation SourceCodeSplitterOrientation {
            get {
                return ((global::System.Windows.Forms.Orientation)(this["SourceCodeSplitterOrientation"]));
            }
            set {
                this["SourceCodeSplitterOrientation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float SourceCodeVerticalSplitterPosition {
            get {
                return ((float)(this["SourceCodeVerticalSplitterPosition"]));
            }
            set {
                this["SourceCodeVerticalSplitterPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.3")]
        public float SourceCodeHorizontalSplitterPosition {
            get {
                return ((float)(this["SourceCodeHorizontalSplitterPosition"]));
            }
            set {
                this["SourceCodeHorizontalSplitterPosition"] = value;
            }
        }
    }
}
