//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCentric.Gui.Model.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class RecentProjectsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static RecentProjectsSettings defaultInstance = ((RecentProjectsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RecentProjectsSettings())));
        
        public static RecentProjectsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int MaxFiles {
            get {
                return ((int)(this["MaxFiles"]));
            }
            set {
                this["MaxFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckFilesExist {
            get {
                return ((bool)(this["CheckFilesExist"]));
            }
            set {
                this["CheckFilesExist"] = value;
            }
        }
    }
}
