//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCentric.Gui.Model.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class TestListSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestListSettings defaultInstance = ((TestListSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestListSettings())));
        
        public static TestListSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OUTCOME")]
        public string GroupBy {
            get {
                return ((string)(this["GroupBy"]));
            }
            set {
                this["GroupBy"] = value;
            }
        }
    }
}
