//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCentric.Gui.Model.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class TestTreeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TestTreeSettings defaultInstance = ((TestTreeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TestTreeSettings())));
        
        public static TestTreeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int InitialTreeDisplay {
            get {
                return ((int)(this["InitialTreeDisplay"]));
            }
            set {
                this["InitialTreeDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classic")]
        public string AlternateImageSet {
            get {
                return ((string)(this["AlternateImageSet"]));
            }
            set {
                this["AlternateImageSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCheckBoxes {
            get {
                return ((bool)(this["ShowCheckBoxes"]));
            }
            set {
                this["ShowCheckBoxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTestDuration {
            get {
                return ((bool)(this["ShowTestDuration"]));
            }
            set {
                this["ShowTestDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NUNIT_TREE")]
        public string DisplayFormat {
            get {
                return ((string)(this["DisplayFormat"]));
            }
            set {
                this["DisplayFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNamespace {
            get {
                return ((bool)(this["ShowNamespace"]));
            }
            set {
                this["ShowNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNGROUPED")]
        public string NUnitGroupBy {
            get {
                return ((string)(this["NUnitGroupBy"]));
            }
            set {
                this["NUnitGroupBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFilter {
            get {
                return ((bool)(this["ShowFilter"]));
            }
            set {
                this["ShowFilter"] = value;
            }
        }
    }
}
