//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCentric.Gui.Model.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    public sealed partial class TextOutputSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TextOutputSettings defaultInstance = ((TextOutputSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TextOutputSettings())));
        
        public static TextOutputSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordWrapEnabled {
            get {
                return ((bool)(this["WordWrapEnabled"]));
            }
            set {
                this["WordWrapEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ON")]
        public string Labels {
            get {
                return ((string)(this["Labels"]));
            }
            set {
                this["Labels"] = value;
            }
        }
    }
}
